dbt_bq_project:
  outputs:
    dev:
      dataset: br_ibge_pnadc
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: bd-practices
      threads: 1
      type: bigquery
  target: dev